### ISSUE TITLE
missing ground truth response?

### ISSUE THREAD

**Issue by yawenouyang** [yfeng21/nota_prediction#1]
I downloaded the dataset and found that there are 11 columns in one row (one context+10 candidates?), which one is the ground truth response?

**Comment by yfeng21** [comment]
Hi,

Ground truth is always the first candidate.

Yulan

On Jun 27, 2020, at 5:08 AM, yawenouyang <notifications@github.com> wrote:

﻿

I downloaded the dataset and found that there are 11 columns in one row (one context+10 candidates?), which one is the ground truth response?

**Comment by yawenouyang** [comment]
I see, thanks!
